# Vector Creation

In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [3]:
arr = np.array(my_list)

In [4]:
arr

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [6]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
# Step by 4 to get to 10
np.arange(0, 10, 4)

array([0, 4, 8])

In [11]:
np.zeros(3)

array([ 0.,  0.,  0.])

In [14]:
# Creating a matrix of 0s
# Give a tuple
# row,columns
np.zeros((5,5))

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [15]:
np.ones(4)

array([ 1.,  1.,  1.,  1.])

In [16]:
np.ones((4,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [18]:
# Do an arange, but have evenly spaced out numbers
# In this example, have 10 evenly spaced points from 0 to 5
np.linspace(0, 5, 10)

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

In [19]:
# Identity Matrix
np.eye(4)

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  1.]])

In [22]:
# Random array
# Create given shape array from random numbers distributed from 0 to 1
np.random.rand(5)

array([ 0.33323845,  0.5252114 ,  0.17805514,  0.82373946,  0.79367298])

In [23]:
np.random.rand(5, 5)

array([[ 0.20100911,  0.2185558 ,  0.16286378,  0.50133271,  0.39101682],
       [ 0.88101948,  0.65020851,  0.76725136,  0.96925859,  0.85434113],
       [ 0.57164412,  0.24454138,  0.10371998,  0.36199167,  0.54903247],
       [ 0.34187585,  0.8926344 ,  0.41520806,  0.58951147,  0.58168294],
       [ 0.38787068,  0.7404816 ,  0.55283736,  0.8497846 ,  0.49384116]])

In [24]:
# Random array from 0 to 1 normal distrubtion , centered around 0
np.random.randn(2)

array([ 1.40029335,  0.76241321])

In [26]:
# Random Integer from range - Inclusive to Exclusive
np.random.randint(1,100)

13

In [28]:
np.random.randint(1,100,10)

array([19, 72, 80, 10, 28, 76, 78, 53, 97, 65])

In [29]:
arr = np.arange(25)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
ranarr = np.random.randint(0, 50, 10)

In [32]:
ranarr

array([ 4, 13, 30, 26,  7, 47, 47, 19, 28, 44])

In [35]:
# Reshape arr
# You'll get an error if you can't fill it properly
# Row x columsn = number of elements in array
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
# Get max
ranarr.max()

47

In [39]:
# Get min
ranarr.min()

4

In [40]:
# Get The index of the max
ranarr.argmax()

5

In [41]:
ranarr.argmin()

0

In [44]:
# Figuring out the shape of a vector
arr.shape

(25,)

In [45]:
ranarr.shape

(10,)

In [46]:
arr = arr.reshape(5,5)

In [47]:
arr.shape

(5, 5)

In [49]:
# Data Type of Vector
arr.dtype

dtype('int64')

In [50]:
arr = np.arange(0, 11)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Indexing & Slicing

In [52]:
arr[8]

8

In [55]:
# Starting Index : Ending Index (0 -> 5)
arr[0:5]

array([0, 1, 2, 3, 4])

In [57]:
# Everything up to index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [60]:
# Grab everything including & beyond index
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [61]:
# Broadcasting or Mapping
arr[0:5] = 100

In [62]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)

In [65]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
slice_of_arr = arr[0:6]

In [67]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [68]:
slice_of_arr[:]

array([0, 1, 2, 3, 4, 5])

In [69]:
slice_of_arr[:] = 99

In [70]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [72]:
# Notice the referencing, there's no copying
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [79]:
# You need to copy
arr_copy = arr.copy()

In [74]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [75]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [76]:
arr_copy[:] = 100

In [77]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [78]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [82]:
# 2d array
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [85]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [86]:
arr_2d[0][0]

5

In [87]:
arr_2d[0]

array([ 5, 10, 15])

In [88]:
arr_2d[2][1]

40

In [89]:
# we can save a bracket and grab using single brackets
arr_2d[2,1]

40

In [90]:
arr_2d[1,2]

30

In [91]:
# Grab everything up to row 2 , grab column 1 and onwards
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [92]:
# If colon before, means grab everything before
# If colon after, means grab everything after
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [93]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

# Conditional Selection 

In [94]:
arr = np.arange(1, 11)

In [95]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
bool_arr = arr > 5

In [98]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,  True], dtype=bool)

In [99]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [100]:
# Shorcut
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [101]:
arr[arr < 3]

array([1, 2])

In [103]:
arr_2d = np.arange(0,50).reshape(5,10)

In [104]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [105]:
# Cut rows 1 & 2 (1 to 3 exlusive)
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [106]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Operations

In [107]:
arr = np.arange(1, 11)

In [108]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [110]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [111]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [113]:
# Scalar addition
arr + 100

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [114]:
arr - 100

array([-99, -98, -97, -96, -95, -94, -93, -92, -91, -90])

In [115]:
arr / arr

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [116]:
arr = np.arange(0,11)

In [117]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
# You'll get a warning for dividing by 0 in numpy
arr/arr

/Users/admin/anaconda2/envs/tensorflow/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in true_divide
  from ipykernel import kernelapp as app


array([ nan,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.,   1.])

In [120]:
1 / arr

/Users/admin/anaconda2/envs/tensorflow/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


array([        inf,  1.        ,  0.5       ,  0.33333333,  0.25      ,
        0.2       ,  0.16666667,  0.14285714,  0.125     ,  0.11111111,
        0.1       ])

In [121]:
# Exponents
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [122]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [123]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [124]:
np.max(arr)

10

In [125]:
arr.max()

10

In [126]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [127]:
np.log(arr)

/Users/admin/anaconda2/envs/tensorflow/lib/python3.5/site-packages/ipykernel/__main__.py:1: RuntimeWarning: divide by zero encountered in log
  if __name__ == '__main__':


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436,
        1.60943791,  1.79175947,  1.94591015,  2.07944154,  2.19722458,
        2.30258509])